import type { LocalizedText, Species } from "./fishing-data";

// Places anglers commonly fish on the Region 2 reaches, gathered by hand from
// public forums, shop reports, videos and OpenStreetMap. Each spot belongs to
// exactly one DFO reach and says nothing about limits: what may be kept there
// always comes from that reach's DFO rules. A spot needs two independent
// sources, or one source and a feature that can be checked on the map.

export type SpotSourceKind = "forum" | "report" | "blog" | "video" | "osm" | "social" | "news" | "official" | "user";

export type SpotSource = {
  title: string;
  url: string;
  kind: SpotSourceKind;
  accessed: string;
};

export type PopularSpotKind = "pool" | "bar" | "access" | "bank";

export type PopularSpot = {
  id: string;
  reach: string;
  name: LocalizedText;
  coordinates: [number, number];
  kind: PopularSpotKind;
  species?: Species[];
  months?: number[];
  access: LocalizedText;
  sources: SpotSource[];
};

const t = (en: string, zh: string): LocalizedText => ({ en, zh });

export const popularSpots: PopularSpot[] = [
  {
    id: "chilliwack-vedder-keith-wilson-bridge",
    reach: "chilliwack-vedder",
    name: t("Keith Wilson Bridge", "Keith Wilson 桥"),
    coordinates: [49.10306, -122.0774],
    kind: "access",
    species: ["Chinook", "Coho", "Chum", "Pink"],
    months: [9, 10, 11],
    access: t("Fish either bank at the Keith Wilson Road bridge over the Vedder Canal; the Vedder Rotary Trail dyke paths run along both banks and cross the bridge. Some canal sections have had seasonal access closures, so check the City of Chilliwack closure map.", "在 Keith Wilson Road 跨 Vedder Canal 的桥两岸均可钓；Vedder Rotary Trail 堤岸步道沿两岸并经过此桥。运河部分河段曾有季节性封闭，出发前请查看 Chilliwack 市封闭地图。"),
    sources: [
      { title: "Vedder / Chilliwack River – Fishing Locations", url: "https://www.bcfishingjournal.com/project/vedder-chilliwack-river-fishing-locations/", kind: "blog", accessed: "2026-10-05" },
      { title: "Chilliwack River Fall Salmon Fishery (Fishing with Rod)", url: "https://www.fishingwithrod.com/articles/river_fishing/chilliwack_river_fall_salmon_fishery.html", kind: "blog", accessed: "2026-10-05" },
      { title: "Chilliwack River, Chilliwack (Fishing with Rod)", url: "https://www.fishingwithrod.com/articles/region_two/chilliwack_river.html", kind: "blog", accessed: "2026-10-05" },
      { title: "Vedder - Keith Wilson Bridge (Fish'n BC)", url: "https://www.fishnbc.com/locations/fishingspotdetails.php?SpotName=Vedder+-+Keith+Wilson+Bridge", kind: "blog", accessed: "2026-10-05" },
      { title: "OSM way 25177148", url: "https://www.openstreetmap.org/way/25177148", kind: "osm", accessed: "2026-10-05" },
    ],
  },
  {
    id: "chilliwack-vedder-fishermans-corner",
    reach: "chilliwack-vedder",
    name: t("Fisherman's Corner", "Fisherman's Corner 钓鱼人角"),
    coordinates: [49.09025, -122.0651],
    kind: "access",
    species: ["Chinook", "Coho"],
    months: [7, 8, 9, 10, 11],
    access: t("Park in the Fisherman's Corner lot at 41851 No. 3 Road, Yarrow, on the south side of the river, then take the short trail from the Vedder dyke down to the water. Keith Wilson Bridge is about 1.9 km downstream along the dyke. It is busy in season, so arrive early.", "在河南岸 Yarrow 的 Fisherman's Corner 停车场（41851 No. 3 Road）停车，从 Vedder 堤岸沿短步道下到河边。沿堤往下游约 1.9 公里是 Keith Wilson 桥。鱼季人多，建议早到。"),
    sources: [
      { title: "Anyone hit the Vedder/Chilliwack river today? (r/fishingBC)", url: "https://www.reddit.com/r/fishingBC/comments/1ul5a02/anyone_hit_the_vedderchilliwack_river_today_and/", kind: "forum", accessed: "2026-10-08" },
      { title: "Question about angling license (Fishing with Rod forum)", url: "https://www.fishingwithrod.com/yabbse/index.php?topic=44312.0", kind: "forum", accessed: "2026-10-08" },
      { title: "Directions at Fishermans Corner (Tom Cochran)", url: "https://tomcochranvagabondphotography.com/featured/directions-at-fishermans-corner-tom-cochran.html", kind: "blog", accessed: "2026-10-08" },
    ],
  },
  {
    id: "chilliwack-vedder-train-bridge-bar",
    reach: "chilliwack-vedder",
    name: t("Train Bridge Bar (BC Electric / railway bridge)", "铁路桥 Train Bridge 砾石滩"),
    coordinates: [49.09187, -122.03756],
    kind: "bar",
    species: ["Chinook", "Coho", "Chum", "Pink"],
    months: [9, 10, 11],
    access: t("Reach the south bank from the end of Bergman Road via the 'Bergman Road Entrance' path to the dyke, then walk downstream to the bar above the rail bridge. Stay off the railway tracks and bridge.", "从 Bergman Road 尽头经 “Bergman Road Entrance” 小路上南岸堤坝，向下游步行至铁路桥上游的砾石滩。请勿进入铁轨或铁路桥。"),
    sources: [
      { title: "Vedder / Chilliwack River – Fishing Locations", url: "https://www.bcfishingjournal.com/project/vedder-chilliwack-river-fishing-locations/", kind: "blog", accessed: "2026-10-05" },
      { title: "Chilliwack River Fall Salmon Fishery (Fishing with Rod)", url: "https://www.fishingwithrod.com/articles/river_fishing/chilliwack_river_fall_salmon_fishery.html", kind: "blog", accessed: "2026-10-05" },
      { title: "Vedder fishing spot list (Fish'n BC)", url: "https://www.fishnbc.com/locations/fishingspots.php?Proxy=Vedder", kind: "blog", accessed: "2026-10-05" },
      { title: "OSM way 25177138", url: "https://www.openstreetmap.org/way/25177138", kind: "osm", accessed: "2026-10-05" },
    ],
  },
  {
    id: "chilliwack-vedder-lickman-road",
    reach: "chilliwack-vedder",
    name: t("Lickman Road (and Vedder River Campground)", "Lickman Road 路尽头 / Vedder River 营地"),
    coordinates: [49.09783, -122.00624],
    kind: "access",
    species: ["Chinook", "Coho", "Chum", "Pink"],
    months: [9, 10, 11],
    access: t("North bank: drive to the end of Lickman Road at the dyke trail and walk to the river. South bank: Vedder River Campground on Giesbrecht Road, with parking before the campground gates.", "北岸：开到 Lickman Road 尽头的堤岸步道，步行到河边。南岸：Giesbrecht Road 上的 Vedder River 营地，营地大门外可停车。"),
    sources: [
      { title: "Vedder / Chilliwack River – Fishing Locations", url: "https://www.bcfishingjournal.com/project/vedder-chilliwack-river-fishing-locations/", kind: "blog", accessed: "2026-10-05" },
      { title: "Chilliwack River, Chilliwack (Fishing with Rod)", url: "https://www.fishingwithrod.com/articles/region_two/chilliwack_river.html", kind: "blog", accessed: "2026-10-05" },
      { title: "Vedder fishing spot list (Fish'n BC)", url: "https://www.fishnbc.com/locations/fishingspots.php?Proxy=Vedder", kind: "blog", accessed: "2026-10-05" },
      { title: "OSM way 200988486 (Lickman Road)", url: "https://www.openstreetmap.org/way/200988486", kind: "osm", accessed: "2026-10-05" },
    ],
  },
  {
    id: "chilliwack-vedder-peach-road",
    reach: "chilliwack-vedder",
    name: t("Peach Road", "Peach Road 钓点"),
    coordinates: [49.09722, -121.98609],
    kind: "access",
    species: ["Chinook", "Coho", "Chum", "Pink"],
    months: [9, 10, 11],
    access: t("Drive to the end of Peach Road at the north dyke, park, and walk a short way to the river. Both banks are fished, and there is more water downstream along the north side.", "开到 Peach Road 尽头的北岸堤坝停车，步行很短距离到河边。两岸都可钓，北岸往下游还有更多钓位。"),
    sources: [
      { title: "Vedder / Chilliwack River – Fishing Locations", url: "https://www.bcfishingjournal.com/project/vedder-chilliwack-river-fishing-locations/", kind: "blog", accessed: "2026-10-05" },
      { title: "Vedder River? (BC Fly Fishing Forums)", url: "https://www.flyfishbc.com/threads/vedder-river.8607/", kind: "forum", accessed: "2026-10-05" },
      { title: "Vedder - Peach Road (Fish'n BC)", url: "https://www.fishnbc.com/locations/fishingspotdetails.php?SpotName=Vedder+-+Peach+Road", kind: "blog", accessed: "2026-10-05" },
      { title: "Chilliwack River Fall Salmon Fishery (Fishing with Rod)", url: "https://www.fishingwithrod.com/articles/river_fishing/chilliwack_river_fall_salmon_fishery.html", kind: "blog", accessed: "2026-10-05" },
    ],
  },
  {
    id: "chilliwack-vedder-vedder-crossing",
    reach: "chilliwack-vedder",
    name: t("Vedder Crossing", "Vedder Crossing 大桥"),
    coordinates: [49.09739, -121.9646],
    kind: "access",
    species: ["Chinook", "Coho", "Chum", "Pink"],
    months: [9, 10, 11],
    access: t("Fishing on both sides of the bridge. There is a parking lot on the southeast side of the bridge, and Vedder Park (free parking) on the north bank just downstream gives access to the run below the bridge.", "桥上下游两岸均可钓。桥东南侧有停车场；北岸下游紧邻的 Vedder Park（免费停车）可通往桥下河段。"),
    sources: [
      { title: "Vedder / Chilliwack River – Fishing Locations", url: "https://www.bcfishingjournal.com/project/vedder-chilliwack-river-fishing-locations/", kind: "blog", accessed: "2026-10-05" },
      { title: "Chilliwack River Fall Salmon Fishery (Fishing with Rod)", url: "https://www.fishingwithrod.com/articles/river_fishing/chilliwack_river_fall_salmon_fishery.html", kind: "blog", accessed: "2026-10-05" },
      { title: "Vedder fishing spot list (Fish'n BC)", url: "https://www.fishnbc.com/locations/fishingspots.php?Proxy=Vedder", kind: "blog", accessed: "2026-10-05" },
      { title: "Vedder Rotary Loop Trail (ihikebc)", url: "https://www.ihikebc.com/trips/2021/trip205-01VedderRotaryLoopTrail.htm", kind: "blog", accessed: "2026-10-05" },
    ],
  },
  {
    id: "chilliwack-vedder-tamihi-bridge-tamihi-pool",
    reach: "chilliwack-vedder",
    name: t("Tamihi Bridge & Tamihi Pool", "Tamihi 桥 / Tamihi 深潭"),
    coordinates: [49.07245, -121.84134],
    kind: "pool",
    species: ["Chinook", "Coho", "Chum"],
    months: [9, 10, 11],
    access: t("Park at Tamihi Creek Recreation Site beside the Chilliwack Lake Road bridge; the pool is just below the bridge and the rapids are above it.", "在 Chilliwack Lake Road 桥旁的 Tamihi Creek 休闲营地停车；深潭就在桥下游，急流在桥上游。"),
    sources: [
      { title: "Vedder / Chilliwack River – Fishing Locations", url: "https://www.bcfishingjournal.com/project/vedder-chilliwack-river-fishing-locations/", kind: "blog", accessed: "2026-10-05" },
      { title: "Chilliwack River Fall Salmon Fishery (Fishing with Rod)", url: "https://www.fishingwithrod.com/articles/river_fishing/chilliwack_river_fall_salmon_fishery.html", kind: "blog", accessed: "2026-10-05" },
      { title: "Vedder - Tamahi Bridge (Fish'n BC)", url: "https://www.fishnbc.com/locations/fishingspotdetails.php?SpotName=Vedder+-+Tamahi+Bridge", kind: "blog", accessed: "2026-10-05" },
      { title: "OSM way 473460949 (Tamihi Creek Recreation Site)", url: "https://www.openstreetmap.org/way/473460949", kind: "osm", accessed: "2026-10-05" },
    ],
  },
  {
    id: "chilliwack-vedder-allison-pool",
    reach: "chilliwack-vedder",
    name: t("Allison Pool", "Allison Pool 营地河段"),
    coordinates: [49.08065, -121.8026],
    kind: "access",
    species: ["Chinook", "Coho", "Chum"],
    months: [9, 10, 11],
    access: t("Recreation site on the left side of Chilliwack Lake Road, about 15 km from Vedder Road, by gravel access; it connects to the Trans Canada Trail. The site is seasonal (Easter to Thanksgiving long weekend).", "位于 Chilliwack Lake Road 左侧的休闲营地，距 Vedder Road 约 15 公里，碎石路进入，可接 Trans Canada Trail。营地为季节性开放（复活节至感恩节长周末）。"),
    sources: [
      { title: "Chilliwack River Fall Salmon Fishery (Fishing with Rod)", url: "https://www.fishingwithrod.com/articles/river_fishing/chilliwack_river_fall_salmon_fishery.html", kind: "blog", accessed: "2026-10-05" },
      { title: "Vedder / Chilliwack River – Fishing Locations", url: "https://www.bcfishingjournal.com/project/vedder-chilliwack-river-fishing-locations/", kind: "blog", accessed: "2026-10-05" },
      { title: "Vedder River (Angler's Atlas)", url: "https://www.anglersatlas.com/place/186102/vedder-river", kind: "blog", accessed: "2026-10-05" },
      { title: "OSM relation 17891882", url: "https://www.openstreetmap.org/relation/17891882", kind: "osm", accessed: "2026-10-05" },
    ],
  },
  {
    id: "chilliwack-vedder-thurston-meadows",
    reach: "chilliwack-vedder",
    name: t("Thurston Meadows", "Thurston Meadows 营地"),
    coordinates: [49.07682, -121.74548],
    kind: "access",
    species: ["Chinook", "Coho", "Chum"],
    months: [9, 10, 11],
    access: t("Recreation site directly off Chilliwack Lake Road on the upper river, with parking and facilities at the site.", "上游河段的休闲营地，直接由 Chilliwack Lake Road 进入，营地内有停车和设施。"),
    sources: [
      { title: "Vedder / Chilliwack River – Fishing Locations", url: "https://www.bcfishingjournal.com/project/vedder-chilliwack-river-fishing-locations/", kind: "blog", accessed: "2026-10-05" },
      { title: "Vedder fishing spot list (Fish'n BC)", url: "https://www.fishnbc.com/locations/fishingspots.php?Proxy=Vedder", kind: "blog", accessed: "2026-10-05" },
      { title: "OSM way 473406600", url: "https://www.openstreetmap.org/way/473406600", kind: "osm", accessed: "2026-10-05" },
    ],
  },
  {
    id: "chehalis-chehalis-river-recreation-site",
    reach: "chehalis",
    name: t("Chehalis River Recreation Site (Morris Valley Road bridge)", "Chehalis River 营地（Morris Valley Rd 桥）"),
    coordinates: [49.29872, -121.93542],
    kind: "access",
    species: ["Coho", "Chum", "Chinook"],
    months: [6, 7, 8, 9, 10, 11],
    access: t("About 5 km up Morris Valley Road from Highway 7 (turn at the Sasquatch Inn). There is a day-use area by the bridge and a campground just downstream with easy foot access. Parking is tight, and trails on the north side of the bridge are posted no trespassing.", "从 7 号公路（Sasquatch Inn 处）转入 Morris Valley Road 约 5 公里。桥边有日间使用区，桥下游有营地，步行即可到河边。停车位紧张；桥北侧小径挂有禁止进入标志。"),
    sources: [
      { title: "Chehalis River, Harrison Mills (Fishing with Rod)", url: "https://www.fishingwithrod.com/articles/region_two/chehalis_river.html", kind: "blog", accessed: "2026-10-05" },
      { title: "Chehalis River (Fishing with Rod forum)", url: "https://www.fishingwithrod.com/yabbse/index.php?topic=41768.0", kind: "forum", accessed: "2026-10-05" },
      { title: "Chehalis River (Sites and Trails BC)", url: "https://www.sitesandtrailsbc.ca/resource/REC0065", kind: "official", accessed: "2026-10-05" },
      { title: "New Chehalis trail (BC Fishing Reports)", url: "https://www.bcfishingreports.com/threads/new-chehalis-trail.13915/", kind: "forum", accessed: "2026-10-05" },
    ],
  },
  {
    id: "harrison-upper-mouth-of-the-chehalis",
    reach: "harrison-upper",
    name: t("Mouth of the Chehalis (Chehalis confluence)", "Chehalis 河口汇流处"),
    coordinates: [49.26117, -121.92086],
    kind: "pool",
    species: ["Coho", "Chum"],
    months: [9, 10, 11],
    access: t("Boat access, typically launching at Kilby Park and running upriver past the Highway 7 bridge. Much of the surrounding shore is private or First Nation land, so fish from the water.", "需乘船前往，一般从 Kilby Park 下水，向上游经过 7 号公路桥。周边岸地多为私人或原住民土地，请在船上垂钓。"),
    sources: [
      { title: "Vancouver Friday Fishing Report, October 12 (Pacific Angler)", url: "https://www.pacificangler.ca/blogs/learn/vancouver-friday-fishing-report-october-12", kind: "report", accessed: "2026-10-05" },
      { title: "Searching For Coho On The Fly From the Harrison River", url: "https://about-flyfishing.com/fly-fishing-destinations/searching-for-coho-on-the-fly-from-the-harrison-river-mission-bc/", kind: "blog", accessed: "2026-10-05" },
      { title: "Harrison River fishing (Fishing with Rod forum)", url: "https://www.fishingwithrod.com/yabbse/index.php?topic=34052.0", kind: "forum", accessed: "2026-10-05" },
    ],
  },
  {
    id: "harrison-upper-morris-slough-mouth",
    reach: "harrison-upper",
    name: t("Morris Slough mouth", "Morris Slough 河口"),
    coordinates: [49.29417, -121.88148],
    kind: "pool",
    species: ["Coho", "Chum"],
    months: [9, 10, 11],
    access: t("Boat or kayak access on the Harrison (for example from Kilby Park). The old road into Morris Lake is closed to vehicles, so there is no practical drive-in shore access.", "需乘船或皮划艇从 Harrison 河进入（例如由 Kilby Park 下水）。通往 Morris Lake 的旧路已禁止车辆通行，没有实际可行的开车到岸边路线。"),
    sources: [
      { title: "Vancouver Friday Fishing Report, October 12 (Pacific Angler)", url: "https://www.pacificangler.ca/blogs/learn/vancouver-friday-fishing-report-october-12", kind: "report", accessed: "2026-10-05" },
      { title: "Searching For Coho On The Fly From the Harrison River", url: "https://about-flyfishing.com/fly-fishing-destinations/searching-for-coho-on-the-fly-from-the-harrison-river-mission-bc/", kind: "blog", accessed: "2026-10-05" },
      { title: "Harrison - Morris Creek (Fish'n BC)", url: "https://www.fishnbc.com/locations/fishingspots.php?Proxy=Vedder", kind: "blog", accessed: "2026-10-05" },
      { title: "Morris Lake access (BC Fishing Reports)", url: "https://www.bcfishingreports.com/threads/morris-lake-access.27738/", kind: "forum", accessed: "2026-10-05" },
    ],
  },
  {
    id: "harrison-lower-kilby-park-harrison-bay",
    reach: "harrison-lower",
    name: t("Kilby Park / Harrison Bay", "Kilby 公园 / Harrison Bay"),
    coordinates: [49.23602, -121.96216],
    kind: "access",
    species: ["Coho", "Chum", "Chinook", "Pink", "Sockeye"],
    months: [8, 9, 10, 11],
    access: t("From Highway 7 just east of the Harrison River bridge, take School Road then Kilby Road to Kilby Park at the west end. There is day-use parking, a beach for shore fishing and a paved boat launch (fee).", "在 Harrison 河桥东侧由 7 号公路转 School Road，再转 Kilby Road 到西端的 Kilby Park。有日间停车场，可在沙滩岸钓，另有收费水泥船坡。"),
    sources: [
      { title: "Harrison River, Agassiz (Fishing with Rod)", url: "https://www.fishingwithrod.com/articles/region_two/harrison_river.html", kind: "blog", accessed: "2026-10-05" },
      { title: "Harrison - Harrison Bay (Fish'n BC)", url: "https://www.fishnbc.com/locations/fishingspotdetails.php?SpotName=Harrison+-+Harrison+Bay", kind: "blog", accessed: "2026-10-05" },
      { title: "Vancouver Friday Fishing Report, October 12 (Pacific Angler)", url: "https://www.pacificangler.ca/blogs/learn/vancouver-friday-fishing-report-october-12", kind: "report", accessed: "2026-10-05" },
      { title: "Harrison River (Angler's Atlas)", url: "https://www.anglersatlas.com/place/186104/harrison-river", kind: "blog", accessed: "2026-10-05" },
      { title: "Kilby Park Campground", url: "https://kilby.ca/campground/", kind: "official", accessed: "2026-10-05" },
    ],
  },
  {
    id: "harrison-lower-harrison-river-mouth",
    reach: "harrison-lower",
    name: t("Harrison River mouth (Fraser confluence)", "Harrison 河口（汇入 Fraser）"),
    coordinates: [49.2292, -121.9453],
    kind: "bank",
    species: ["Chinook", "Coho", "Chum", "Pink", "Sockeye"],
    months: [8, 9, 10, 11],
    access: t("Boat-only: launch at Kilby Park or at Island 22 on the Fraser and run to where the clear Harrison meets the Fraser. There is no road access.", "只能乘船：从 Kilby Park 或 Fraser 河上的 Island 22 下水，开到清澈的 Harrison 河与 Fraser 河交汇处。没有道路可达。"),
    sources: [
      { title: "Harrison - River Mouth (Fish'n BC)", url: "https://www.fishnbc.com/locations/fishingspotdetails.php?SpotName=Harrison+-+River+Mouth", kind: "blog", accessed: "2026-10-05" },
      { title: "Kilby boat Launch to Harrison Lake (BC Fishing Reports)", url: "https://www.bcfishingreports.com/threads/kilby-boat-launch-to-harrison-lake.21186/", kind: "forum", accessed: "2026-10-05" },
    ],
  },
  {
    id: "stave-toilet-bowl-east-side-below-ruskin-dam",
    reach: "stave",
    name: t("Toilet Bowl / east side below Ruskin Dam", "Ruskin 坝下东岸 / Toilet Bowl（马桶潭）"),
    coordinates: [49.19395, -122.4106],
    kind: "pool",
    species: ["Chum", "Coho"],
    months: [10, 11, 12],
    access: t("East side via the BC Hydro Ruskin picnic site off Hayward Street (gated; closed for slope-repair construction, with BC Hydro expecting reopening in fall 2026). Fish the main river only; the Ruskin spawning channel beside the picnic area is closed.", "东岸经 Hayward Street 旁的 BC Hydro Ruskin 野餐区进入（有闸门；因边坡修复施工关闭，BC Hydro 预计 2026 年秋季重开）。只能在主河道垂钓；野餐区旁的 Ruskin 产卵渠禁钓。"),
    sources: [
      { title: "Stave River Fishing Locations and Species (BC Fishing Journal)", url: "https://www.bcfishingjournal.com/project/stave-river-fishing-locations-and-species/", kind: "blog", accessed: "2026-10-05" },
      { title: "stave river cutthroat (Fishing with Rod forum)", url: "https://www.fishingwithrod.com/yabbse/index.php?topic=23261.0", kind: "forum", accessed: "2026-10-05" },
      { title: "Stave River water levels below Ruskin dam (Fishing with Rod forum)", url: "https://www.fishingwithrod.com/yabbse/index.php?topic=41495.0", kind: "forum", accessed: "2026-10-05" },
      { title: "Ruskin Dam (BC Hydro)", url: "https://www.bchydro.com/community/recreation_areas/ruskin_dam.html", kind: "official", accessed: "2026-10-05" },
    ],
  },
  {
    id: "stave-west-side-upper-run",
    reach: "stave",
    name: t("West side upper run (Wilson Street)", "Stave 西岸上游河段（Wilson Street）"),
    coordinates: [49.18957, -122.41075],
    kind: "bank",
    species: ["Chum", "Coho"],
    months: [10, 11, 12],
    access: t("Short walk from Wilson Street on the west side; waders recommended. Parking is enforced in salmon season, so use legal spots only. Do not fish the Northrop Channel or the Thompson Creek fishway area.", "从西岸 Wilson Street 步行很短距离即达，建议穿涉水裤。三文鱼季节有停车执法，请只停合法车位。Northrop 渠及 Thompson Creek 鱼道一带禁止垂钓。"),
    sources: [
      { title: "Stave River Fishing Locations and Species (BC Fishing Journal)", url: "https://www.bcfishingjournal.com/project/stave-river-fishing-locations-and-species/", kind: "blog", accessed: "2026-10-05" },
      { title: "Vancouver Friday Fishing Report, October 12 (Pacific Angler)", url: "https://www.pacificangler.ca/blogs/learn/vancouver-friday-fishing-report-october-12", kind: "report", accessed: "2026-10-05" },
      { title: "Stave River Fishing (River Fishing BC)", url: "https://www.riverfishingbc.com/article5.php", kind: "blog", accessed: "2026-10-05" },
    ],
  },
  {
    id: "norrish-norrish-creek-train-bridge",
    reach: "norrish",
    name: t("Norrish Creek train bridge (Hawkins Pickle Road)", "Norrish Creek 铁路桥（Hawkins Pickle Rd）"),
    coordinates: [49.17567, -122.14932],
    kind: "access",
    species: ["Coho", "Chum"],
    months: [10, 11],
    access: t("Off Highway 7 at Dewdney via Hawkins Pickle Road to the road bridge; fish around the road and rail bridges and work upstream. Stay off the railway; the gravel-pit route is private and posted. Large-scale gravel extraction has been reported at these bridges since about 2022.", "在 Dewdney 由 7 号公路转 Hawkins Pickle Road 到公路桥，在公路桥和铁路桥一带垂钓，可向上游走。请勿进入铁路；砾石场路线为私人土地并挂有标志。据报道，自约 2022 年起这两座桥附近有大规模挖砂作业。"),
    sources: [
      { title: "Norrish Creek (BC Fly Fishing Forums)", url: "https://www.flyfishbc.com/threads/norrish-creek.6523/", kind: "forum", accessed: "2026-10-05" },
      { title: "Norrish Creek (Fish'n BC)", url: "https://www.fishnbc.com/locations/fishingspotdetails.php?SpotName=Norrish+Creek", kind: "blog", accessed: "2026-10-05" },
      { title: "Watershed Watch letter to DFO re Norrish Creek", url: "https://watershedwatch.ca/wp-content/uploads/2025/06/Letter-to-DFO-re-Norrish-Creek.pdf", kind: "news", accessed: "2026-10-05" },
      { title: "OSM way 35497771", url: "https://www.openstreetmap.org/way/35497771", kind: "osm", accessed: "2026-10-05" },
    ],
  },
  {
    id: "nicomen-highway-7-bridge-dykes",
    reach: "nicomen",
    name: t("Highway 7 (Dewdney) bridge dykes", "7号公路 Dewdney 桥两岸堤坝"),
    coordinates: [49.16308, -122.19335],
    kind: "bank",
    species: ["Coho", "Chum"],
    months: [10, 11, 12],
    access: t("Walk the dykes on either side of the slough from the Highway 7 bridge at Dewdney; upstream sections are reached via small roads and dykes. The slough is tidal, so fish arrive on the incoming tide.", "从 Dewdney 的 7 号公路桥沿河两侧堤坝步行垂钓；上游河段经小路和堤坝进入。此段受潮汐影响，涨潮时鱼会进来。"),
    sources: [
      { title: "Nicomen Slough, Deroche to Dewdney (Fishing with Rod)", url: "https://www.fishingwithrod.com/articles/region_two/nicomen_slough.html", kind: "blog", accessed: "2026-10-05" },
      { title: "nicomen slough (BC Fishing Reports)", url: "https://www.bcfishingreports.com/threads/nicomen-slough.7419/", kind: "forum", accessed: "2026-10-05" },
      { title: "OSM way 1324252886", url: "https://www.openstreetmap.org/way/1324252886", kind: "osm", accessed: "2026-10-05" },
    ],
  },
  {
    id: "nicomen-dewdney-regional-park-boat-launch",
    reach: "nicomen",
    name: t("Dewdney Regional Park boat launch (slough mouth)", "Dewdney 区域公园船坡（Slough 出口）"),
    coordinates: [49.14353, -122.18191],
    kind: "access",
    species: ["Coho", "Chum"],
    months: [10, 11, 12],
    access: t("FVRD park at 7840 River Road South (via River Road from Highway 7), with a boat launch, trailer parking and seasonal hours (opens 7 am from mid-October). Cast or bar-fish from shore near the launch, but stay upstream of the slough/Fraser boundary signs below it.", "FVRD 公园，地址 7840 River Road South（由 7 号公路转 River Road），有船坡、拖车停车场，开放时间随季节变化（10 月中起早上 7 点开门）。可在船坡附近岸边抛投或沉底钓，但请留在下游 Slough 与 Fraser 分界标志的上游一侧。"),
    sources: [
      { title: "Dewdney Regional Park (FVRD)", url: "https://www.fvrd.ca/EN/main/parks-recreation/parks-trails/dewdney.html", kind: "official", accessed: "2026-10-05" },
      { title: "Nicomen Slough, Deroche to Dewdney (Fishing with Rod)", url: "https://www.fishingwithrod.com/articles/region_two/nicomen_slough.html", kind: "blog", accessed: "2026-10-05" },
      { title: "nicomen slough (BC Fishing Reports)", url: "https://www.bcfishingreports.com/threads/nicomen-slough.7419/", kind: "forum", accessed: "2026-10-05" },
      { title: "Nicomen Slough (Fishing with Rod forum)", url: "https://www.fishingwithrod.com/yabbse/index.php?topic=44657.0", kind: "forum", accessed: "2026-10-05" },
    ],
  },
  {
    id: "capilano-cable-pool",
    reach: "capilano",
    name: t("Cable Pool (tailout below the footbridge)", "Cable Pool（缆索潭，人行桥下游潭尾）"),
    coordinates: [49.3546, -123.1109],
    kind: "pool",
    species: ["Coho", "Chinook"],
    months: [6, 7, 8, 9, 10, 11],
    access: t("Park at the Capilano River Hatchery main lot (4500 Capilano Park Rd). Take the staircase/trail down to the pool tailout. Fish only downstream of the footbridge; the area above it is signed closed.", "在 Capilano River Hatchery 主停车场（4500 Capilano Park Rd）停车，沿楼梯/步道下到潭尾。只能在人行桥下游钓鱼，桥上游有封闭标志。"),
    sources: [
      { title: "Capilano River BC Canada (thread)", url: "https://www.sportfishingbc.com/threads/capilano-river-bc-canada.81422/", kind: "forum", accessed: "2026-10-05" },
      { title: "Capilano River – summer coho salmon", url: "https://bcfishingjournal.com/journals/capilano-river-summer-coho-salmon/", kind: "blog", accessed: "2026-10-05" },
      { title: "Fishing with Rod forum – Capilano (topic 39972)", url: "https://www.fishingwithrod.com/yabbse/index.php?topic=39972.0", kind: "forum", accessed: "2026-10-05" },
      { title: "Fishing with Rod forum – Capilano (topic 44544)", url: "https://www.fishingwithrod.com/yabbse/index.php?topic=44544.0", kind: "forum", accessed: "2026-10-05" },
      { title: "OSM Cable Pool water area", url: "https://www.openstreetmap.org/way/1532071080", kind: "osm", accessed: "2026-10-05" },
    ],
  },
  {
    id: "capilano-dogleg-pool",
    reach: "capilano",
    name: t("Dogleg Pool", "Dogleg Pool（狗腿潭）"),
    coordinates: [49.3533, -123.1127],
    kind: "pool",
    species: ["Coho"],
    months: [6, 7, 8, 9, 10, 11],
    access: t("From the hatchery parking lot, walk downstream on the Coho Loop / Pipeline Trail (Capilano River Regional Park) to the bend. The banks are steep and rocky.", "从孵化场停车场沿 Coho Loop / Pipeline Trail（Capilano River Regional Park）向下游步行到河湾处。河岸陡峭多石。"),
    sources: [
      { title: "Capilano River BC Canada (thread)", url: "https://www.sportfishingbc.com/threads/capilano-river-bc-canada.81422/", kind: "forum", accessed: "2026-10-05" },
      { title: "Fishing with Rod forum (topic 18114)", url: "https://www.fishingwithrod.com/yabbse/index.php?topic=18114.0", kind: "forum", accessed: "2026-10-05" },
      { title: "OSM Dogleg Pool", url: "https://www.openstreetmap.org/node/13963138008", kind: "osm", accessed: "2026-10-05" },
    ],
  },
  {
    id: "capilano-doctor-s-pool",
    reach: "capilano",
    name: t("Doctor's Pool (Keith Road / under Highway 1)", "Doctor's Pool（Keith Road／1号公路桥下）"),
    coordinates: [49.33309, -123.11848],
    kind: "pool",
    species: ["Coho", "Chinook"],
    months: [7, 8, 9, 10, 11],
    access: t("West side: from the end of Keith Rd off Taylor Way, park under the highway bridge. East side: from the Woods Dr pocket off Capilano Rd. Watch the side channel and island: dam releases can strand anglers.", "西岸：从 Taylor Way 进入 Keith Rd 尽头，在高速桥下停车。东岸：从 Capilano Rd 旁的 Woods Dr 小停车处进入。注意侧汊和小岛，大坝放水时可能被困。"),
    sources: [
      { title: "Treat moving water with respect; find a backcountry mentor", url: "https://vancouversun.com/news/local-news/treat-moving-water-with-respect-find-a-backcountry-mentor", kind: "news", accessed: "2026-10-05" },
      { title: "Capilano River – Fishing with Rod article", url: "https://www.fishingwithrod.com/articles/region_two/capilano_river.html", kind: "blog", accessed: "2026-10-05" },
      { title: "How do I get here? (r/fishingBC)", url: "https://www.reddit.com/r/fishingBC/comments/1gcl2fc/how_do_i_get_here/", kind: "forum", accessed: "2026-10-05" },
      { title: "Fishing with Rod forum (topic 33651)", url: "https://www.fishingwithrod.com/yabbse/index.php?topic=33651.0", kind: "forum", accessed: "2026-10-05" },
    ],
  },
  {
    id: "coquitlam-red-bridge",
    reach: "coquitlam",
    name: t("Red Bridge (Pitt River Road)", "Red Bridge（红桥，Pitt River Road）"),
    coordinates: [49.25084, -122.79657],
    kind: "access",
    species: ["Coho", "Chum"],
    months: [10, 11, 12],
    access: t("Park near the Pitt River Rd bridge and walk the PoCo Trail along either bank. Stay upstream of the Mary Hill Bypass (tidal water) and do not cross the rail line farther south.", "在 Pitt River Rd 桥附近停车，沿 PoCo Trail 走两岸。留在 Mary Hill Bypass 上游（下游为潮汐水域），不要穿越南面的铁路。"),
    sources: [
      { title: "The last row of 2014 – rowing up the Coquitlam River to the Red Bridge", url: "https://urbanoarsman.com/the-last-row-of-2014-the-urban-oarsman-rows-up-the-coquitlam-river-to-the-red-bridge/", kind: "blog", accessed: "2026-10-05" },
      { title: "SportfishingBC thread 71518", url: "https://www.sportfishingbc.com/threads/71518/", kind: "forum", accessed: "2026-10-05" },
      { title: "OSM Pitt River Road bridge over Coquitlam River", url: "https://www.openstreetmap.org/#map=18/49.25084/-122.79657", kind: "osm", accessed: "2026-10-05" },
    ],
  },
  {
    id: "coquitlam-hockaday-park-bank",
    reach: "coquitlam",
    name: t("Hockaday Park bank", "Hockaday Park 河岸"),
    coordinates: [49.29905, -122.76867],
    kind: "bank",
    species: ["Coho", "Chum"],
    months: [10, 11, 12],
    access: t("Enter from Hockaday Park (off Hockaday St, Coquitlam) and follow the trail to the river's west bank.", "从 Hockaday Park（Coquitlam，Hockaday St 旁）进入，沿步道到河西岸。"),
    sources: [
      { title: "Hockaday Park – City of Coquitlam", url: "https://www.coquitlam.ca/Facilities/Facility/Details/Hockaday-Park-46", kind: "official", accessed: "2026-10-05" },
      { title: "Salmon spotting in the Tri-Cities – PSF", url: "https://www.psf.ca/blog/salmon-spotting-tricities/", kind: "blog", accessed: "2026-10-05" },
      { title: "OSM Hockaday Park", url: "https://www.openstreetmap.org/way/483567949", kind: "osm", accessed: "2026-10-05" },
    ],
  },
  {
    id: "coquitlam-galette-park-bank",
    reach: "coquitlam",
    name: t("Galette Park bank", "Galette Park 河岸"),
    coordinates: [49.30289, -122.76932],
    kind: "bank",
    species: ["Coho", "Chum"],
    months: [10, 11, 12],
    access: t("Enter from Galette Park at Galette Ave, Coquitlam. A short path leads to the west bank.", "从 Coquitlam Galette Ave 的 Galette Park 进入，短步道通往河西岸。"),
    sources: [
      { title: "Galette Park – City of Coquitlam", url: "https://www.coquitlam.ca/Facilities/Facility/Details/Galette-Park-38", kind: "official", accessed: "2026-10-05" },
      { title: "OSM Galette Park", url: "https://www.openstreetmap.org/way/217022330", kind: "osm", accessed: "2026-10-05" },
    ],
  },
  {
    id: "alouette-lower-jerry-sulina-park-dyke",
    reach: "alouette-lower",
    name: t("Jerry Sulina Park dyke", "Jerry Sulina Park 堤岸"),
    coordinates: [49.24822, -122.64088],
    kind: "bank",
    species: ["Coho", "Chum"],
    months: [10, 11, 12],
    access: t("Park at Jerry Sulina Park (13180 210 St, Maple Ridge). The public dyke trail runs downstream from here to Harris Rd. The bank upstream of the park toward 216 St is private.", "在 Jerry Sulina Park（Maple Ridge，13180 210 St）停车。公共堤岸步道从这里向下游通到 Harris Rd。公园上游至 216 St 一段为私人土地。"),
    sources: [
      { title: "Jerry Sulina Park – City of Maple Ridge", url: "https://www.mapleridge.ca/art-parks-rec/recreation-facilities/jerry-sulina-park", kind: "official", accessed: "2026-10-05" },
      { title: "Fishing on the Alouette River (r/MapleRidge)", url: "https://www.reddit.com/r/MapleRidge/comments/1d96ex0/fishing_on_the_alouette_river/", kind: "forum", accessed: "2026-10-05" },
    ],
  },
  {
    id: "alouette-lower-neaves-road-bridge",
    reach: "alouette-lower",
    name: t("Neaves Road bridge (west-side tree line)", "Neaves Road 桥（西侧树林岸）"),
    coordinates: [49.24911, -122.64479],
    kind: "access",
    species: ["Coho", "Chum"],
    months: [10, 11, 12],
    access: t("Park at the first Neaves Rd bridge north of Lougheed Hwy. Walk the dyke a short way west to the tree-lined bank. Snags are common.", "在 Lougheed Hwy 以北 Neaves Rd 的第一座桥停车，沿堤向西走一小段到树林岸。水下障碍较多。"),
    sources: [
      { title: "Fishing on the Alouette River (r/MapleRidge)", url: "https://www.reddit.com/r/MapleRidge/comments/1d96ex0/fishing_on_the_alouette_river/", kind: "forum", accessed: "2026-10-05" },
      { title: "Fishing the Alouette River (BC Fishing Reports)", url: "https://www.bcfishingreports.com/threads/fishing-the-alouette-river.4803/", kind: "forum", accessed: "2026-10-05" },
    ],
  },
  {
    id: "alouette-lower-harris-road-dyke",
    reach: "alouette-lower",
    name: t("Harris Road (Silver Bridge) dyke", "Harris Road（Silver Bridge）堤岸"),
    coordinates: [49.26457, -122.68928],
    kind: "access",
    species: ["Coho", "Chum"],
    months: [10, 11, 12],
    access: t("Use the parking lot and kayak launch at the Harris Rd bridge in Pitt Meadows. Walk the dyke trails up- or downstream.", "使用 Pitt Meadows Harris Rd 桥旁的停车场和皮划艇下水点，沿堤岸步道向上游或下游走。"),
    sources: [
      { title: "Fishing the Alouette River (BC Fishing Reports)", url: "https://www.bcfishingreports.com/threads/fishing-the-alouette-river.4803/", kind: "forum", accessed: "2026-10-05" },
      { title: "Fishing on the Alouette River (r/MapleRidge)", url: "https://www.reddit.com/r/MapleRidge/comments/1d96ex0/fishing_on_the_alouette_river/", kind: "forum", accessed: "2026-10-05" },
      { title: "North Alouette River – AllTrails", url: "https://www.alltrails.com/poi/canada/british-columbia/pitt-meadows/north-alouette-river", kind: "blog", accessed: "2026-10-05" },
    ],
  },
  {
    id: "alouette-upper-davidson-s-pool-hot-rocks",
    reach: "alouette-upper",
    name: t("Davidson's Pool / Hot Rocks", "Davidson's Pool／Hot Rocks（热石滩）"),
    coordinates: [49.23727, -122.56596],
    kind: "pool",
    species: ["Coho", "Chinook"],
    months: [9, 10, 11],
    access: t("City parking at 23701 128 Cres, Maple Ridge (Davidson's Pool). Hot Rocks is just upstream, off Fern Cres. In summer this is a busy swimming and tubing spot, so fish in fall.", "Maple Ridge 23701 128 Cres（Davidson's Pool）有市政停车场。Hot Rocks 在上游不远处，Fern Cres 旁。夏季这里游泳、漂流的人很多，建议秋季来钓。"),
    sources: [
      { title: "Best River for Steelhead (Fishing with Rod forum)", url: "https://www.fishingwithrod.com/yabbse/index.php?topic=9302.0", kind: "forum", accessed: "2026-10-05" },
      { title: "Fishing the Alouette River (BC Fishing Reports)", url: "https://www.bcfishingreports.com/threads/fishing-the-alouette-river.4803/", kind: "forum", accessed: "2026-10-05" },
      { title: "Swimming and fishing don't mix (Maple Ridge News)", url: "https://mapleridgenews.com/2013/07/12/swimming-and-fishing-dont-mix/", kind: "news", accessed: "2026-10-05" },
      { title: "Davidson's Pool – City of Maple Ridge", url: "https://www.mapleridge.ca/art-parks-rec/recreation-facilities/davidsons-pool", kind: "official", accessed: "2026-10-05" },
    ],
  },
  {
    id: "kanaka-below-240-st-rainbow-bridge",
    reach: "kanaka",
    name: t("Below 240 St – Rainbow Bridge", "240 St 下游 – Rainbow Bridge"),
    coordinates: [49.20107, -122.56587],
    kind: "access",
    species: ["Coho", "Chum"],
    months: [10, 11],
    access: t("Kanaka Creek Regional Park trails between 240 St and Lougheed Hwy. Stay well clear of the fish fence at the 240 St bridge. The creek rises fast after rain.", "Kanaka Creek Regional Park 位于 240 St 与 Lougheed Hwy 之间的步道。远离 240 St 桥旁的数鱼栅。雨后水位上涨很快。"),
    sources: [
      { title: "Got any tips for fishing Kanaka Creek, Maple Ridge? (BC Fly Fishing Forums)", url: "https://www.flyfishbc.com/threads/got-any-tips-for-fishing-kanaka-creek-maple-ridge.5222/", kind: "forum", accessed: "2026-10-05" },
      { title: "OSM Rainbow Bridge (Kanaka Creek)", url: "https://www.openstreetmap.org/way/182649800", kind: "osm", accessed: "2026-10-05" },
    ],
  },
  {
    id: "de-boville-de-boville-slough-mouth",
    reach: "de-boville",
    name: t("De Boville Slough mouth (Pitt River end)", "De Boville Slough 汇入口（Pitt River 端）"),
    coordinates: [49.27916, -122.70981],
    kind: "bank",
    species: ["Coho", "Chum"],
    months: [9, 10],
    access: t("Park at the gravel lot at Victoria Dr & Cedar Dr, Coquitlam. Walk the north-side DeBoville Slough Dyke trail to the slough mouth (about 25 minutes on foot, 10 by bike).", "在 Coquitlam Victoria Dr 与 Cedar Dr 交界的碎石停车场停车，沿北侧 DeBoville Slough Dyke 步道走到汇入口（步行约25分钟，骑车约10分钟）。"),
    sources: [
      { title: "DeBoville Slough, Coquitlam – Fishing with Rod", url: "https://www.fishingwithrod.com/articles/region_two/deboville_slough.html", kind: "blog", accessed: "2026-10-05" },
      { title: "OSM De Boville Slough and DeBoville Slough Dyke trail", url: "https://www.openstreetmap.org/way/72833113", kind: "osm", accessed: "2026-10-05" },
    ],
  },
  {
    id: "squamish-fisherman-s-park",
    reach: "squamish",
    name: t("Fisherman's Park (Judd Road)", "Fisherman's Park 钓鱼人公园（Judd Road）"),
    coordinates: [49.75762, -123.15697],
    kind: "bank",
    species: ["Pink", "Chum", "Coho"],
    months: [8, 9, 10, 11, 12],
    access: t("Park in the lot at the end of Judd Road in Brackendale and take the short trail to the sandy beach. Don't follow the dyke upstream: the riverbank there is posted Squamish Nation land, and the park across the river discourages angling while eagles are present (Nov–Feb).", "在 Brackendale 的 Judd Road 尽头停车场停车，沿短步道走到河边沙滩。不要沿堤坝往上游走：那一段河岸是挂了告示的 Squamish Nation 土地；对岸省立公园在老鹰季（11–2月）不鼓励钓鱼。"),
    sources: [
      { title: "Fishing in Squamish, BC", url: "https://www.exploresquamish.com/things-to-do/activities-adventures/fishing/", kind: "official", accessed: "2026-10-05" },
      { title: "Squamish River & Tributaries Fishing Locations", url: "https://www.bcfishingjournal.com/project/squamish-river-tributaries/", kind: "blog", accessed: "2026-10-05" },
      { title: "Pink Salmon Squamish River and Tributaries", url: "https://www.bcfishingjournal.com/journals/pink-salmon-squamish-river-and-tributaries/", kind: "blog", accessed: "2026-10-05" },
      { title: "Squamish - Judd Rd??", url: "https://www.bcfishingreports.com/threads/squamish-judd-rd.20117/", kind: "forum", accessed: "2026-10-05" },
      { title: "1st trip to... SQUAMISH RIVER and need help", url: "https://sportfishingbc.com/threads/1st-trip-to-squamish-river-and-need-help.67507/", kind: "forum", accessed: "2026-10-05" },
      { title: "OSM Fisherman's Beach", url: "https://www.openstreetmap.org/node/13895060835", kind: "osm", accessed: "2026-10-05" },
    ],
  },
  {
    id: "squamish-mamquam-squamish-confluence",
    reach: "squamish",
    name: t("Mamquam–Squamish confluence (Upper/Lower Mamquam Bar)", "Mamquam 与 Squamish 汇流处砾石滩"),
    coordinates: [49.73376, -123.15364],
    kind: "bar",
    species: ["Pink", "Chinook", "Chum", "Coho"],
    months: [7, 8, 9, 10, 11],
    access: t("From Government Road, cross the tracks at the public road crossing into the Edgewater streets, then walk north on the Squamish River dyke to its end at the Mamquam mouth (a few hundred metres of dirt path). Don't use the gravel track at the CN Mamquam bridge, which crosses the main line at grade.", "从 Government Road 经公路平交道口进入 Edgewater 社区，再沿 Squamish 河堤向北走到 Mamquam 河口（最后几百米为土路）。不要走 CN 铁路桥旁的碎石路，那条路要直接横穿铁路干线。"),
    sources: [
      { title: "Fishing in Squamish, BC", url: "https://www.exploresquamish.com/things-to-do/activities-adventures/fishing/", kind: "official", accessed: "2026-10-05" },
      { title: "Squamish River & Tributaries Fishing Locations", url: "https://www.bcfishingjournal.com/project/squamish-river-tributaries/", kind: "blog", accessed: "2026-10-05" },
      { title: "Squamish - Upper Mamquam Bar", url: "https://www.fishnbc.com/locations/fishingspotdetails.php?SpotName=Squamish+-+Upper+Mamquam+Bar", kind: "report", accessed: "2026-10-05" },
      { title: "Squamish - Lower Mamquam Bar", url: "https://www.fishnbc.com/locations/fishingspotdetails.php?SpotName=Squamish+-+Lower+Mamquam+Bar", kind: "report", accessed: "2026-10-05" },
    ],
  },
  {
    id: "squamish-squamish-riverside-recreation-site",
    reach: "squamish",
    name: t("Squamish Riverside Recreation Site (Ashlu Road bridge)", "Squamish Riverside 休闲营地（Ashlu Road 桥）"),
    coordinates: [49.91524, -123.29406],
    kind: "access",
    species: ["Pink", "Coho", "Chum"],
    months: [8, 9, 10, 11],
    access: t("Drive Squamish Valley Road and the Squamish River FSR, turn left onto the Ashlu FSR and cross the Squamish River bridge; the free rec site is immediately on the right, with a small beach. The road is rough (avoid low-clearance vehicles), and the site closes when bears are active.", "沿 Squamish Valley Road 和 Squamish River FSR 行驶，左转上 Ashlu FSR，过 Squamish River 桥后右手边即是免费营地，旁边有小沙滩。路况颠簸，低底盘车不建议；有熊出没时营地会关闭。"),
    sources: [
      { title: "Squamish Riverside Campsite (REC0265)", url: "https://www.sitesandtrailsbc.ca/resource/REC0265", kind: "official", accessed: "2026-10-05" },
      { title: "The Squamish River FSR", url: "https://takemetotheriver.ca/road-trips/squamish-river-fsr", kind: "blog", accessed: "2026-10-05" },
      { title: "Squamish River & Tributaries Fishing Locations", url: "https://www.bcfishingjournal.com/project/squamish-river-tributaries/", kind: "blog", accessed: "2026-10-05" },
      { title: "OSM Squamish Riverside Campground", url: "https://www.openstreetmap.org/way/1201198774", kind: "osm", accessed: "2026-10-05" },
    ],
  },
  {
    id: "mamquam-government-road-hole",
    reach: "mamquam",
    name: t("Government Road Hole (Mamquam)", "Government Road 桥上游深潭（Mamquam）"),
    coordinates: [49.73102, -123.14397],
    kind: "pool",
    species: ["Pink", "Chinook", "Chum", "Coho"],
    months: [8, 9, 10, 11, 12],
    access: t("Park off the west side of Government Road just north of the Mamquam bridge and walk a few metres upstream to the main river. The spawning channels just upstream are closed to fishing, so stay on the mainstem.", "在 Government Road 的 Mamquam 桥北侧路西停车，往上游走几米即到主河道。上游不远处的产卵渠禁止钓鱼，只在主河道钓。"),
    sources: [
      { title: "Mamquam - Government Road Hole", url: "https://www.fishnbc.com/locations/fishingspotdetails.php?SpotName=Mamquam+-+Government+Road+Hole", kind: "report", accessed: "2026-10-05" },
      { title: "Mamquam Spawning Channels", url: "https://www.squamishtrails.ca/trail-blog/mamquam-spawning-channels", kind: "blog", accessed: "2026-10-05" },
      { title: "OSM Government Road bridge", url: "https://www.openstreetmap.org/way/41929407", kind: "osm", accessed: "2026-10-05" },
    ],
  },
  {
    id: "mamquam-golf-course-run",
    reach: "mamquam",
    name: t("Golf Course Run (Mamquam River Trails)", "高尔夫球场段（Golf Course Run，Mamquam River Trails）"),
    coordinates: [49.72771, -123.12005],
    kind: "bank",
    species: ["Pink", "Chinook", "Chum", "Coho"],
    months: [8, 9, 10, 11, 12],
    access: t("Use the Mamquam River trailhead on Mamquam Road (about 1.4 km from Hwy 99, just past the golf course, before Mashiter Creek; small lot with toilet) and follow the dyke trails' side paths to the river. The spawning channels along the trail are closed to fishing.", "从 Mamquam Road 上的 Mamquam River 步道口进入（距 99 号公路约 1.4 km，过高尔夫球场、Mashiter Creek 之前，有小停车场和厕所），沿堤坝步道的支路走到河边。步道旁的产卵渠禁止钓鱼。"),
    sources: [
      { title: "Mamquam - Golf Course Run", url: "https://www.fishnbc.com/locations/fishingspotdetails.php?SpotName=Mamquam+-+Golf+Course+Run", kind: "report", accessed: "2026-10-05" },
      { title: "Squamish River & Tributaries Fishing Locations", url: "https://www.bcfishingjournal.com/project/squamish-river-tributaries/", kind: "blog", accessed: "2026-10-05" },
      { title: "Mamquam River Trails", url: "https://www.exploresquamish.com/trails/mamquam-river-trails/", kind: "official", accessed: "2026-10-05" },
    ],
  },
  {
    id: "cheakamus-bailey-bridge",
    reach: "cheakamus",
    name: t("Bailey Bridge (BC Hydro bridge, Paradise Valley Road)", "Bailey 桥（BC Hydro 桥，Paradise Valley Road）"),
    coordinates: [49.82713, -123.15332],
    kind: "access",
    species: ["Chum", "Coho", "Pink"],
    months: [9, 10, 11, 12],
    access: t("Take Squamish Valley Road, keep right onto Paradise Valley Road and park near the second bridge; fish around the bridge from the east bank. Don't walk the railway, and stay off the Cheakamus Centre (Outdoor School) land and side channels west and south of the bridge, which are posted private.", "走 Squamish Valley Road，岔路靠右上 Paradise Valley Road，在第二座桥附近停车，从东岸在桥周边钓。不要沿铁路走；桥西、桥南的 Cheakamus Centre（户外学校）土地和侧渠为私人地，已挂告示，不要进入。"),
    sources: [
      { title: "Cheakamus River, Whistler to Squamish", url: "https://fishingwithrod.com/articles/region_two/cheakamus_river.html", kind: "blog", accessed: "2026-10-05" },
      { title: "1st trip to... SQUAMISH RIVER and need help", url: "https://sportfishingbc.com/threads/1st-trip-to-squamish-river-and-need-help.67507/", kind: "forum", accessed: "2026-10-05" },
      { title: "Squamish Fishing", url: "https://www.flyfishbc.com/threads/squamish-fishing.6598/", kind: "forum", accessed: "2026-10-05" },
      { title: "Squamish/Cheakamus/Mamquam - Fish in the system?", url: "https://www.bcfishingreports.com/threads/squamish-cheakamus-mamquam-fish-in-the-system.7525/", kind: "forum", accessed: "2026-10-05" },
      { title: "Squamish River & Tributaries Fishing Locations", url: "https://www.bcfishingjournal.com/project/squamish-river-tributaries/", kind: "blog", accessed: "2026-10-05" },
    ],
  },
  {
    id: "ashlu-creek-ashlu-main-bridge",
    reach: "ashlu-creek",
    name: t("Ashlu main bridge (below the generating station)", "Ashlu 主桥（发电站下游）"),
    coordinates: [49.91053, -123.32166],
    kind: "access",
    species: ["Coho", "Chum", "Chinook"],
    months: [9, 10, 11],
    access: t("Follow the Ashlu River FSR west past the Squamish Riverside rec site to the main bridge just below the power plant, park at the roadside and fish above and below the bridge. There's no road between the bridge and the creek mouth, and trails there are rough.", "沿 Ashlu River FSR 向西，经过 Squamish Riverside 营地，到发电站下方的主桥，在路边停车，在桥上下游钓。桥到河口之间没有道路，小径崎岖。"),
    sources: [
      { title: "Squamish River & Tributaries Fishing Locations", url: "https://www.bcfishingjournal.com/project/squamish-river-tributaries/", kind: "blog", accessed: "2026-10-05" },
      { title: "A Peek at Ashlu Creek", url: "https://tothewild.com/ashlu-creek/", kind: "blog", accessed: "2026-10-05" },
      { title: "OSM Ashlu River FSR bridge", url: "https://www.openstreetmap.org/way/41929018", kind: "osm", accessed: "2026-10-05" },
    ],
  },
  {
    id: "chapman-chapman-creek-pools-above-the-hwy-101-bridge",
    reach: "chapman",
    name: t("Chapman Creek pools above the Hwy 101 bridge (Brookman Park)", "Chapman Creek 101 号公路桥上游水潭（Brookman Park）"),
    coordinates: [49.44226, -123.72107],
    kind: "pool",
    species: ["Coho"],
    months: [9, 10, 11, 12, 1],
    access: t("Park at Brookman Park on Hwy 101 just east of Davis Bay beach and walk upstream on the Chapman Creek Trail to the pools. Stay well away from the hatchery and its adult trap upstream; the beach and estuary below the bridge are tidal water, outside this reach.", "在 Davis Bay 海滩东侧、101 号公路旁的 Brookman Park 停车，沿 Chapman Creek 步道往上游走找水潭。离上游的孵化场及其成鱼捕获设施保持足够距离；公路桥以下的海滩和河口属潮水区，不在本河段内。"),
    sources: [
      { title: "Lake Finishing (r/Sechelt)", url: "https://www.reddit.com/r/Sechelt/comments/yrrpd2/lake_finishing/", kind: "forum", accessed: "2026-10-05" },
      { title: "Chapman Creek Trail", url: "https://www.trailpeak.com/trails/chapman-creek-trail-near-sechelt-bc-216", kind: "blog", accessed: "2026-10-05" },
      { title: "Chapman Creek Fish Whisperer Gear Loan Program", url: "https://scsalmon.org/community/chapman-creek-fish-whisperer-gear-loan-program", kind: "report", accessed: "2026-10-05" },
      { title: "Adult Salmon Returns", url: "https://scsalmon.org/adult-salmon-returns", kind: "report", accessed: "2026-10-05" },
    ],
  },
  {
    id: "serpentine-serpentine-fen-riverbank",
    reach: "serpentine",
    name: t("Serpentine Fen riverbank (below the King George sea dam)", "Serpentine Fen 湿地河岸（King George 海坝下游）"),
    coordinates: [49.0866, -122.8229],
    kind: "bank",
    species: ["Chinook", "Coho"],
    months: [9, 10, 11],
    access: t("Park in the small gravel lot off King George Blvd at the 4600 block (near 44 Ave), then walk about 600 m north on the Fen trail to the south-bank dyke. Keep well back from the sea-dam flood gates, where signs prohibit fishing.", "在 King George Blvd 4600 号段（近 44 Ave）的碎石停车场停车，沿 Fen 步道向北步行约 600 米到南岸堤坝。请远离海坝闸门，那里有禁钓标志。"),
    sources: [
      { title: "Serpentine Wildlife Management Area", url: "https://www.surrey.ca/parks-recreation/parks/serpentine-wildlife-management-area", kind: "official", accessed: "2026-10-05" },
      { title: "Delta Naturalists Outing to Serpentine Fen, September 16, 2025", url: "https://deltanaturalists.org/2025/09/16/delta-naturalists-outing-to-serpentine-fen-september-16-2025/", kind: "blog", accessed: "2026-10-05" },
      { title: "Delta Naturalists Outing to Serpentine Fen, September 15, 2026", url: "https://deltanaturalists.org/2026/09/16/delta-naturalists-outing-to-serpentine-fen-september-152026/", kind: "blog", accessed: "2026-10-05" },
      { title: "Serpentine river (Fishing with Rod forum)", url: "https://www.fishingwithrod.com/yabbse/index.php?topic=21465.0", kind: "forum", accessed: "2026-10-05" },
      { title: "OpenStreetMap: Serpentine Sea Dam, Fen trail, towers and parking", url: "https://www.openstreetmap.org/way/704791015", kind: "osm", accessed: "2026-10-05" },
    ],
  },
  {
    id: "nicomekl-elgin-heritage-park-ward-s-marina-dock",
    reach: "nicomekl",
    name: t("Elgin Heritage Park – Ward's Marina dock", "Elgin Heritage Park（Ward's 码头浮台）"),
    coordinates: [49.06677, -122.8434],
    kind: "access",
    species: ["Coho", "Chinook"],
    months: [9, 10, 11],
    access: t("Free parking at Historic Stewart Farm / Elgin Heritage Park, 13723 Crescent Road. Walk about 150 m to the public marina float and boat ramp. It is shared with paddlers and boaters, so give launching boats room.", "在 Crescent Road 13723 号 Historic Stewart Farm / Elgin Heritage Park 免费停车，步行约 150 米到公共码头浮台和下水坡道。码头与划艇和船只共用，请给下水的船让出空间。"),
    sources: [
      { title: "Nicomekl river (SportFishing BC forum)", url: "https://sportfishingbc.com/threads/nicomekl-river.83416/", kind: "forum", accessed: "2026-10-05" },
      { title: "Fishing in the Nicomekl River between Crescent Beach Marina and Wards Marina", url: "https://www.fishingwithrod.com/yabbse/index.php?topic=45490.0", kind: "forum", accessed: "2026-10-05" },
      { title: "Ward's Public Marina Boat Launch | Fish'n BC", url: "https://www.fishnbc.com/resources/wards.html", kind: "blog", accessed: "2026-10-05" },
      { title: "OpenStreetMap: Ward's Marina pier", url: "https://www.openstreetmap.org/way/238919308", kind: "osm", accessed: "2026-10-05" },
    ],
  },
  {
    id: "nicomekl-nicomekl-greenway-dyke-along-nico-wynd-golf-course",
    reach: "nicomekl",
    name: t("Nicomekl Greenway dyke along Nico-Wynd Golf Course", "Nico-Wynd 高尔夫球场旁的 Nicomekl Greenway 堤岸"),
    coordinates: [49.07152, -122.8303],
    kind: "bank",
    species: ["Coho", "Chinook"],
    months: [9, 10, 11],
    access: t("Walk east from the Elgin Heritage Park lot (Crescent Road) on the public Nicomekl Greenway dyke, which runs between the river and Nico-Wynd Golf Course. Stay on the dyke side and off the golf course, which is private.", "从 Elgin Heritage Park 停车场（Crescent Road）沿公共 Nicomekl Greenway 堤岸步道向东走，步道夹在河与 Nico-Wynd 高尔夫球场之间。请留在堤岸一侧，不要进入高尔夫球场（私人场地）。"),
    sources: [
      { title: "Nicomekl river (SportFishing BC forum)", url: "https://sportfishingbc.com/threads/nicomekl-river.83416/", kind: "forum", accessed: "2026-10-05" },
      { title: "Boundary Bay & Mud Bay Floodplains | City of Surrey", url: "https://www.surrey.ca/services-payments/water-drainage-sewer/flood-control/lowlands-floodplains/boundary-bay-mud-bay-floodplains", kind: "official", accessed: "2026-10-05" },
      { title: "OpenStreetMap: Nicomekl Greenway", url: "https://www.openstreetmap.org/way/86463250", kind: "osm", accessed: "2026-10-05" },
    ],
  },
];

export const popularSpotsOn = (reachId: string) => popularSpots.filter((spot) => spot.reach === reachId);
